include_guard(GLOBAL)

file(GLOB_RECURSE MYPLAYER_CPP_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/app/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/core/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/features/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/ui/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/common/*.cpp"
)

file(GLOB_RECURSE MYPLAYER_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/app/*.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/core/*.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/features/*.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/ui/*.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/common/*.h"
)

set(MYPLAYER_QT_FILES
    "${CMAKE_CURRENT_SOURCE_DIR}/app/ui/my_player.ui"
    "${CMAKE_CURRENT_SOURCE_DIR}/app/ui/my_player.qrc"
)

set(MYPLAYER_CUDA_FILES
    "${CMAKE_CURRENT_SOURCE_DIR}/features/detector/cuda_preprocess.cu"
)

set(MYPLAYER_SOURCE_FILES
    ${MYPLAYER_CPP_SOURCES}
    ${MYPLAYER_HEADERS}
    ${MYPLAYER_QT_FILES}
    ${MYPLAYER_CUDA_FILES}
)

list(SORT MYPLAYER_SOURCE_FILES)

set(MYPLAYER_INCLUDE_DIRS
    "${CMAKE_CURRENT_SOURCE_DIR}"
    "${MYPLAYER_LOCAL_INCLUDE_DIR}"
    "${MYPLAYER_CUDA_INCLUDE_DIR}"
    ${MYPLAYER_FFMPEG_INCLUDE_DIRS}
    "${MYPLAYER_ONNXRUNTIME_INCLUDE_DIR}"
    "${MYPLAYER_WHISPER_INCLUDE_DIR}"
    "${MYPLAYER_LIBASS_INCLUDE_DIR}"
)

if(EXISTS "${MYPLAYER_BYTETRACK_SOURCE_DIR}/include/bytetrack")
    list(APPEND MYPLAYER_INCLUDE_DIRS "${MYPLAYER_BYTETRACK_SOURCE_DIR}/include/bytetrack")
else()
    list(APPEND MYPLAYER_INCLUDE_DIRS "${MYPLAYER_LOCAL_INCLUDE_DIR}/bytetrack")
endif()

foreach(source_file IN LISTS MYPLAYER_CPP_SOURCES MYPLAYER_HEADERS)
    get_filename_component(source_dir "${source_file}" DIRECTORY)
    list(APPEND MYPLAYER_INCLUDE_DIRS "${source_dir}")
endforeach()

list(REMOVE_DUPLICATES MYPLAYER_INCLUDE_DIRS)
